[package]
name = "pna_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
calamine = "0.32.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
